workflows:
  android-release:
    name: Build Android Release APK
    max_build_duration: 60
    environment:
      flutter: stable
      android:
        build_tool: gradle
      vars:
        FLUTTER_BUILD_MODE: release
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Analyze project
        script: flutter analyze
      - name: Build release APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
